polls/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from .views import *
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('',inicio, name='inicio'),
    path('inicio/',inicio, name='inicio'),

    path('editarintegrante/<str:pk>/', editarintegrante, name='editarintegrante'),
    path('eliminarintegrante/<str:pk>/', eliminarintegrante, name='eliminarintegrante'),
    path('agregarintegrante/', agregarintegrante, name='agregarintegrante'),
    path('agregargrupo/', agregargrupo, name='agregargrupo'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prueba_scrummers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    
    path('', include('polls.urls')),
    
    path('admin/', admin.site.urls),
    
    
] 

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('', include('django.contrib.auth.urls')),
]

polls/models.py
from django.db import models
from smart_selects.db_fields import ChainedForeignKey

# Create your models here.


class Grupodetrabajo(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, unique=True )
    maxnumero = models.IntegerField()
    minnumero = models.IntegerField()
    def __str__(self):
        return self.nombre 
    @property
    def get_integrantes(self):
        integrantes = self.integrantes_set.all()
        
        return integrantes

class Integrantes(models.Model):
    id = models.AutoField(primary_key=True)
    imagen = models.ImageField()
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    descripcion = models.TextField(max_length=300)
    grupodetrabajo = models.ForeignKey(Grupodetrabajo, on_delete=models.CASCADE, null=True, to_field='nombre')
    def __str__(self):
        return self.nombres  

polls/forms.py
from django import forms
from django.forms import ModelForm
from .models import *



class IntegrantesForm(ModelForm):
   
   class Meta:
      model = Integrantes
      fields = ['imagen','nombres','apellidos','descripcion','grupodetrabajo']    
      widgets = {
       'imagen': forms.FileInput(attrs={'class':'input100','placeholder':'Imagen'}), 
       'nombres': forms.TextInput(attrs={'class':'input100','placeholder':'Nombres'}),
       'apellidos': forms.TextInput(attrs={'class':'input100','placeholder':'Apellidos'}),
       'descripcion': forms.TextInput(attrs={'class':'input100','placeholder':'Describete'}),
       'grupodetrabajo': forms.Select(attrs={'class':'input100','placeholder':'Grupo'}),

      }



class GruposForm(ModelForm):
   
   class Meta:
      model = Grupodetrabajo
      fields = ['nombre','maxnumero','minnumero']    
      widgets = {
       'nombre': forms.TextInput(attrs={'class':'input100','placeholder':'Nombre'}),
       'maxnumero': forms.NumberInput(attrs={'class':'input100','placeholder':'Integrantes maximo'}),
       'minnumero': forms.NumberInput(attrs={'class':'input100','placeholder':'Integrantes minimo'}),

      }

polls/views.py
from polls.models import *
from django.shortcuts import render, redirect
from .forms import  *
from django.contrib import messages

# Create your views here.
def inicio(request):
  model=Grupodetrabajo.objects.filter()
  model2=Integrantes.objects.filter().values('id','nombres','apellidos','descripcion','grupodetrabajo','imagen')
 
  return render(request, 'index.html',{'model':model,'model2':model2})


def eliminarintegrante(request, pk):
	integrante = Integrantes.objects.get(id=pk)	
	integrante.delete()
	return redirect('inicio')


def editarintegrante(request, pk):
  integrante = Integrantes.objects.get(id=pk)
  form = IntegrantesForm(instance=integrante)
  if request.method == 'POST':
    integrante.nombres = request.POST["nombres"]
    integrante.apellidos = request.POST["apellidos"]
    integrante.descripcion = request.POST["descripcion"]
    integrante.imagen = request.FILES["imagen"]
    grupo = Grupodetrabajo.objects.get(nombre=request.POST["grupodetrabajo"])
    integrante.grupodetrabajo = grupo
    integrante.save()
    messages.success(request,"Cambios guardados")
    return redirect('inicio')

  context = {'form':form}
  return render(request, 'Registrointegrantes.html', context)

def agregarintegrante(request):
  form = IntegrantesForm()
  if request.method == 'POST':
    grupo = Grupodetrabajo.objects.get(nombre=request.POST["grupodetrabajo"])
    newintegrante = Integrantes.objects.create(nombres=request.POST["nombres"],apellidos=request.POST["apellidos"],descripcion=request.POST["descripcion"],imagen=request.FILES["imagen"],grupodetrabajo=grupo)
    return redirect('inicio')

  context = {'form':form}
  return render(request, 'Registrointegrantes.html', context)


def agregargrupo(request):
  form = GruposForm()
  if request.method == 'POST':
    form = GruposForm(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request,"Cambios guardados")
        return redirect('inicio')
    messages.success(request,"Cambios no guardados")
    return redirect('inicio')

  context = {'form':form}
  return render(request, 'Registrogrupo.html', context)

polls/templates/Registrogrupos.html
{% load static %}
{% load bootstrap4 %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!doctype html>
<!------ Include the above in your HEAD tag ---------->
<head>
 <title> Personalizacion </title>
 	<title>Personalizacion</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
 <!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'midireccion/images/icons/favicon.ico' %}"/>
 <!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/vendor/bootstrap/css/bootstrap.min.css' %}">
 <!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
 <!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/vendor/animate/animate.css' %}">
 <!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/vendor/css-hamburgers/hamburgers.min.css' %}">
 <!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/vendor/select2/select2.min.css' %}">
 <!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/css/main.css' %}">
 <!--===============================================================================================-->
</head>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="alert alert-warning"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
  
<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
			
				<form action="" enctype="multipart/form-data" method="POST">{% csrf_token %}
	
			
					  <span class="login100-form-title">
					      Formulario integrantes
					  </span>				   
		
					<div class="wrap-input100 validate-input" data-validate = "caracter no permetido">
					   <input type="hidden" name="sitioid" value="{{Sitio.id}}" required="" id="id_nombre">
					   {{form}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
					
						</span>
					</div>



                   

                  {% if messages %}
                     <ul class="messages">
                          {% for message in messages %}
                             <li{% if message.tags %} class="alert alert-success"{% endif %}>{{ message }}</li>
                          {% endfor %}
                     </ul>
                  {% endif %}


					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Guardar
						</button>
					</div>

                </form>

					<div class="text-center p-t-136">
						<a class="txt2" href="/misitio">
							Volver
							<i class="fa fa-arrow-left" aria-hidden="true"></i>
						</a>
					</div>
				
			</div>
		</div>
	</div>


  <!--===============================================================================================-->	
	<script src="/static/login/vendor/jquery/jquery-3.2.1.min.js"></script>
  <!--===============================================================================================-->
	<script src="/static/login/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/login/vendor/bootstrap/js/bootstrap.min.js"></script>
  <!--===============================================================================================-->
	<script src="/static/login/vendor/select2/select2.min.js"></script>
  <!--===============================================================================================-->
	<script src="/static/login/vendor/tilt/tilt.jquery.min.js"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
  <!--===============================================================================================-->
	<script src="js/main.js"></script>
    {% bootstrap_javascript jquery='full' %}
</body>

polls/templates/Registrointegrantes.html
{% load static %}
{% load bootstrap4 %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!doctype html>
<!------ Include the above in your HEAD tag ---------->
<head>
 <title> Personalizacion </title>
 	<title>Personalizacion</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
 <!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'midireccion/images/icons/favicon.ico' %}"/>
 <!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/vendor/bootstrap/css/bootstrap.min.css' %}">
 <!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
 <!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/vendor/animate/animate.css' %}">
 <!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/vendor/css-hamburgers/hamburgers.min.css' %}">
 <!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/vendor/select2/select2.min.css' %}">
 <!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'midireccion/css/main.css' %}">
 <!--===============================================================================================-->
</head>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="alert alert-warning"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
  
<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
			
				<form action="" enctype="multipart/form-data" method="POST">{% csrf_token %}
	
			
					  <span class="login100-form-title">
					      Formulario integrantes
					  </span>				   
		
					<div class="wrap-input100 validate-input" data-validate = "caracter no permetido">
					   <input type="hidden" name="sitioid" value="{{Sitio.id}}" required="" id="id_nombre">
					   {{form}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
					
						</span>
					</div>



                   

                  {% if messages %}
                     <ul class="messages">
                          {% for message in messages %}
                             <li{% if message.tags %} class="alert alert-success"{% endif %}>{{ message }}</li>
                          {% endfor %}
                     </ul>
                  {% endif %}


					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Guardar
						</button>
					</div>

                </form>

					<div class="text-center p-t-136">
						<a class="txt2" href="/misitio">
							Volver
							<i class="fa fa-arrow-left" aria-hidden="true"></i>
						</a>
					</div>
				
			</div>
		</div>
	</div>


  <!--===============================================================================================-->	
	<script src="/static/login/vendor/jquery/jquery-3.2.1.min.js"></script>
  <!--===============================================================================================-->
	<script src="/static/login/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/login/vendor/bootstrap/js/bootstrap.min.js"></script>
  <!--===============================================================================================-->
	<script src="/static/login/vendor/select2/select2.min.js"></script>
  <!--===============================================================================================-->
	<script src="/static/login/vendor/tilt/tilt.jquery.min.js"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
  <!--===============================================================================================-->
	<script src="js/main.js"></script>
    {% bootstrap_javascript jquery='full' %}
</body>

polls/templates/index.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Sentra - Free Bootstrap Theme</title>
        
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="/static/bootstrap.min.css">
        <link rel="stylesheet" href="/static/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/static/fontAwesome.css">
        <link rel="stylesheet" href="/static/light-box.css">
        <link rel="stylesheet" href="/static/owl-carousel.css">
        <link rel="stylesheet" href="/static/templatemo-style.css">

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

        <script src="/static/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
    </head>

<body>



    <header class="nav-down responsive-nav hidden-lg hidden-md">
        <button type="button" id="nav-toggle" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <!--/.navbar-header-->

    </header>

    <div class="sidebar-navigation hidde-sm hidden-xs">
        <div class="logo">
            <a href="#">Prueba<em>tecnica</em></a>
        </div>
        <nav>
            <ul>
                <li>
                    <form id="contact" action="/inicio/" method="post">
                    <a href="/inicio/">
                        <span class="rect"></span>
                        <span class="circle"></span>
                        SCRUMMERS
                    </a>
                    </form>
                </li>

            </ul>
        </nav>

    </div>
    <div class="page-content">
        <section id="contact" class="content-section">
            <div id="contact-content">
            <div class="section-heading">
                <form id="contact" action="/cantidaditems/" method="post">{% csrf_token %}
                <h1>Ejemplo de<br><em>tablas</em></h1>
                <P><br><em>He creado dos tablas, GRUPOS E INTEGRANTES, integrantes tiene llave foranea de grupos </em>{{Sitio.imagenes_set.all.count}}</P>
    
                </form>
                
            </div>

                <div class="section-content">
                        <div class="row">
                            <div class="col-md-6">
                              <form id="contact" action="/agregargrupo/" method="get">
                              <fieldset>
                                  <button type="submit" id="form-submit"  href="/registrarimagensitio/" class="btn">Agregar grupo</button>
                              </fieldset>
                              </form>
                            </div>
                            <div class="col-md-6">
                             <form  action="/agregarintegrante/" method="get">
                              <fieldset>
                                <button type="submit" id="form-submit" class="btn">agregar miembro</button>
                              </fieldset>
                             </form>
                            </div>
                     
                        </div>                   
                </div>
            </div>
        </section>
        <section id="blog" class="content-section">
        {% if messages %}
            <ul class="messages">
              {% for message in messages %}
                <li{% if message.tags %} class="alert alert-warning"{% endif %}>{{ message }}</li>
              {% endfor %}
            </ul>
        {% endif %}             
            <div class="section-content">
                <div class="tabs-content">
                    <div class="wrapper">
                  

                     
                        <br>                        
                      
                        <ul class="tabs" data-tabgroup="first-tab-group">
                  
                            <li><a href="#table1" class="active" >Equipo de trabajo</a></li>
             
     
                        </ul>
                        
                        <section id="first-tab-group" class="tabgroup">\
                            {% for items in model2%}
                            <div id="{{items.grupodetrabajo}}">
                                <ul>
                                   
                                    <li>
                                        <div class="item">
                                            <img src="/media/{{items.imagen}}" width='200px' height='200px' style="border: 5px solid #c78d21; margin-rigth:10px; " alt="">
                                            <div class="text-content">
                                                <h4>{{items.nombres}} {{items.apellidos}}</h4>
                                                <span>Grupo : {{items.grupodetrabajo}}</span>
                                                <p>{{items.descripcion}}</p>
                                                
                                                <div class="accent-button button">
                                                    <a href="{% url 'eliminarintegrante' items.id %}">Eliminar</a>
                                                    <a href="{% url 'editarintegrante' items.id %}">Modificar</a>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    

                                </ul>
                            </div>
                            {% endfor %}

                        </section> 
                    </div>
                </div>
            </div>
        </section>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

    <script src="/static/js/vendor/bootstrap.min.js"></script>
    
    <script src="/static/js/plugins.js"></script>
    <script src="/static/js/main.js"></script>

    <script>
        // Hide Header on on scroll down
        var didScroll;
        var lastScrollTop = 0;
        var delta = 5;
        var navbarHeight = $('header').outerHeight();

        $(window).scroll(function(event){
            didScroll = true;
        });

        setInterval(function() {
            if (didScroll) {
                hasScrolled();
                didScroll = false;
            }
        }, 250);

        function hasScrolled() {
            var st = $(this).scrollTop();
            
            // Make sure they scroll more than delta
            if(Math.abs(lastScrollTop - st) <= delta)
                return;
            
            // If they scrolled down and are past the navbar, add class .nav-up.
            // This is necessary so you never see what is "behind" the navbar.
            if (st > lastScrollTop && st > navbarHeight){
                // Scroll Down
                $('header').removeClass('nav-down').addClass('nav-up');
            } else {
                // Scroll Up
                if(st + $(window).height() < $(document).height()) {
                    $('header').removeClass('nav-up').addClass('nav-down');
                }
            }
            
            lastScrollTop = st;
        }
    </script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>

</body>
</html>